
package web.learning.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWsService", targetNamespace = "http://ws.webservices/", wsdlLocation = "http://localhost:8081/WebServices/TestWs?wsdl")
public class TestWsService
    extends Service
{

    private final static URL TESTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTWSSERVICE_EXCEPTION;
    private final static QName TESTWSSERVICE_QNAME = new QName("http://ws.webservices/", "TestWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WebServices/TestWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWSSERVICE_WSDL_LOCATION = url;
        TESTWSSERVICE_EXCEPTION = e;
    }

    public TestWsService() {
        super(__getWsdlLocation(), TESTWSSERVICE_QNAME);
    }

    public TestWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWSSERVICE_QNAME, features);
    }

    public TestWsService(URL wsdlLocation) {
        super(wsdlLocation, TESTWSSERVICE_QNAME);
    }

    public TestWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWSSERVICE_QNAME, features);
    }

    public TestWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWs
     */
    @WebEndpoint(name = "TestWsPort")
    public TestWs getTestWsPort() {
        return super.getPort(new QName("http://ws.webservices/", "TestWsPort"), TestWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWs
     */
    @WebEndpoint(name = "TestWsPort")
    public TestWs getTestWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.webservices/", "TestWsPort"), TestWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWSSERVICE_EXCEPTION!= null) {
            throw TESTWSSERVICE_EXCEPTION;
        }
        return TESTWSSERVICE_WSDL_LOCATION;
    }

}
