
package web.learning.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWs", targetNamespace = "http://ws.webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGreeting", targetNamespace = "http://ws.webservices/", className = "web.learning.client.GetGreeting")
    @ResponseWrapper(localName = "getGreetingResponse", targetNamespace = "http://ws.webservices/", className = "web.learning.client.GetGreetingResponse")
    public String getGreeting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
