//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.08.20 at 07:44:46 PM COT 
//


package com.millicom.activator.api.dto.portation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for country.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="country"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SLV"/&gt;
 *     &lt;enumeration value="GTM"/&gt;
 *     &lt;enumeration value="HND"/&gt;
 *     &lt;enumeration value="BOL"/&gt;
 *     &lt;enumeration value="COL"/&gt;
 *     &lt;enumeration value="PRY"/&gt;
 *     &lt;enumeration value="TCD"/&gt;
 *     &lt;enumeration value="COG"/&gt;
 *     &lt;enumeration value="GHA"/&gt;
 *     &lt;enumeration value="MUS"/&gt;
 *     &lt;enumeration value="RWA"/&gt;
 *     &lt;enumeration value="SEN"/&gt;
 *     &lt;enumeration value="TZA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "country")
@XmlEnum
public enum Country {

    SLV,
    GTM,
    HND,
    BOL,
    COL,
    PRY,
    TCD,
    COG,
    GHA,
    MUS,
    RWA,
    SEN,
    TZA;

    public String value() {
        return name();
    }

    public static Country fromValue(String v) {
        return valueOf(v);
    }

}
