//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.08.20 at 07:44:46 PM COT 
//


package com.millicom.activator.api.dto.portation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.millicom.activator.api.dto.portation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateTransactionCompleteResultMsg_QNAME = new QName("http://soap.jaxws.ea.htc.com/", "UpdateTransactionCompleteResultMsg");
    private final static QName _UpdateTransactionCompleteResultOperation_QNAME = new QName("http://soap.jaxws.ea.htc.com/", "UpdateTransactionCompleteResultOperation");
    private final static QName _Updatedate_QNAME = new QName("http://soap.jaxws.ea.htc.com/", "Updatedate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.millicom.activator.api.dto.portation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateTransactionCompleteRequest }
     * 
     */
    public UpdateTransactionCompleteRequest createUpdateTransactionCompleteRequest() {
        return new UpdateTransactionCompleteRequest();
    }

    /**
     * Create an instance of {@link UpdateTransactionCompleteResultMsg }
     * 
     */
    public UpdateTransactionCompleteResultMsg createUpdateTransactionCompleteResultMsg() {
        return new UpdateTransactionCompleteResultMsg();
    }

    /**
     * Create an instance of {@link UpdateTransactionCompleteRequestHeader }
     * 
     */
    public UpdateTransactionCompleteRequestHeader createUpdateTransactionCompleteRequestHeader() {
        return new UpdateTransactionCompleteRequestHeader();
    }

    /**
     * Create an instance of {@link UpdateTransactionCompleteRequest.UpdateTransactionCompleteRequestBody }
     * 
     */
    public UpdateTransactionCompleteRequest.UpdateTransactionCompleteRequestBody createUpdateTransactionCompleteRequestUpdateTransactionCompleteRequestBody() {
        return new UpdateTransactionCompleteRequest.UpdateTransactionCompleteRequestBody();
    }

    /**
     * Create an instance of {@link com.millicom.activator.api.dto.portation.UpdateTransactionCompleteRequestBody }
     * 
     */
    public com.millicom.activator.api.dto.portation.UpdateTransactionCompleteRequestBody createUpdateTransactionCompleteRequestBody() {
        return new com.millicom.activator.api.dto.portation.UpdateTransactionCompleteRequestBody();
    }

    /**
     * Create an instance of {@link Updatedate }
     * 
     */
    public Updatedate createUpdatedate() {
        return new Updatedate();
    }

    /**
     * Create an instance of {@link com.millicom.activator.api.dto.portation.UpdateTransactionCompleteResult }
     * 
     */
    public com.millicom.activator.api.dto.portation.UpdateTransactionCompleteResult createUpdateTransactionCompleteResult() {
        return new com.millicom.activator.api.dto.portation.UpdateTransactionCompleteResult();
    }

    /**
     * Create an instance of {@link UpdateTransactionCompleteResultOperation }
     * 
     */
    public UpdateTransactionCompleteResultOperation createUpdateTransactionCompleteResultOperation() {
        return new UpdateTransactionCompleteResultOperation();
    }

    /**
     * Create an instance of {@link Number }
     * 
     */
    public Number createNumber() {
        return new Number();
    }

    /**
     * Create an instance of {@link Reasons }
     * 
     */
    public Reasons createReasons() {
        return new Reasons();
    }

    /**
     * Create an instance of {@link AdditionalParameters }
     * 
     */
    public AdditionalParameters createAdditionalParameters() {
        return new AdditionalParameters();
    }

    /**
     * Create an instance of {@link UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult }
     * 
     */
    public UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult createUpdateTransactionCompleteResultMsgUpdateTransactionCompleteResult() {
        return new UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTransactionCompleteResultMsg }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTransactionCompleteResultMsg }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.jaxws.ea.htc.com/", name = "UpdateTransactionCompleteResultMsg")
    public JAXBElement<UpdateTransactionCompleteResultMsg> createUpdateTransactionCompleteResultMsg(UpdateTransactionCompleteResultMsg value) {
        return new JAXBElement<UpdateTransactionCompleteResultMsg>(_UpdateTransactionCompleteResultMsg_QNAME, UpdateTransactionCompleteResultMsg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTransactionCompleteResultOperation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTransactionCompleteResultOperation }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.jaxws.ea.htc.com/", name = "UpdateTransactionCompleteResultOperation")
    public JAXBElement<UpdateTransactionCompleteResultOperation> createUpdateTransactionCompleteResultOperation(UpdateTransactionCompleteResultOperation value) {
        return new JAXBElement<UpdateTransactionCompleteResultOperation>(_UpdateTransactionCompleteResultOperation_QNAME, UpdateTransactionCompleteResultOperation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Updatedate }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Updatedate }{@code >}
     */
    @XmlElementDecl(namespace = "http://soap.jaxws.ea.htc.com/", name = "Updatedate")
    public JAXBElement<Updatedate> createUpdatedate(Updatedate value) {
        return new JAXBElement<Updatedate>(_Updatedate_QNAME, Updatedate.class, null, value);
    }

}
