//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.08.20 at 07:44:46 PM COT 
//


package com.millicom.activator.api.dto.portation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateTransactionCompleteResultMsg complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateTransactionCompleteResultMsg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="updateTransactionCompleteResultOperation" type="{http://soap.jaxws.ea.htc.com/}updateTransactionCompleteResultOperation" minOccurs="0"/&gt;
 *         &lt;element name="UpdateTransactionCompleteResult" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UpdateTransactionCompleteResponse" type="{http://soap.jaxws.ea.htc.com/}updateTransactionCompleteResultOperation" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateTransactionCompleteResultMsg", propOrder = {
    "updateTransactionCompleteResultOperation",
    "updateTransactionCompleteResult"
})
public class UpdateTransactionCompleteResultMsg {

    protected UpdateTransactionCompleteResultOperation updateTransactionCompleteResultOperation;
    @XmlElement(name = "UpdateTransactionCompleteResult")
    protected UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult updateTransactionCompleteResult;

    /**
     * Gets the value of the updateTransactionCompleteResultOperation property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateTransactionCompleteResultOperation }
     *     
     */
    public UpdateTransactionCompleteResultOperation getUpdateTransactionCompleteResultOperation() {
        return updateTransactionCompleteResultOperation;
    }

    /**
     * Sets the value of the updateTransactionCompleteResultOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateTransactionCompleteResultOperation }
     *     
     */
    public void setUpdateTransactionCompleteResultOperation(UpdateTransactionCompleteResultOperation value) {
        this.updateTransactionCompleteResultOperation = value;
    }

    /**
     * Gets the value of the updateTransactionCompleteResult property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult }
     *     
     */
    public UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult getUpdateTransactionCompleteResult() {
        return updateTransactionCompleteResult;
    }

    /**
     * Sets the value of the updateTransactionCompleteResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult }
     *     
     */
    public void setUpdateTransactionCompleteResult(UpdateTransactionCompleteResultMsg.UpdateTransactionCompleteResult value) {
        this.updateTransactionCompleteResult = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UpdateTransactionCompleteResponse" type="{http://soap.jaxws.ea.htc.com/}updateTransactionCompleteResultOperation" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "updateTransactionCompleteResponse"
    })
    public static class UpdateTransactionCompleteResult {

        @XmlElement(name = "UpdateTransactionCompleteResponse")
        protected UpdateTransactionCompleteResultOperation updateTransactionCompleteResponse;

        /**
         * Gets the value of the updateTransactionCompleteResponse property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTransactionCompleteResultOperation }
         *     
         */
        public UpdateTransactionCompleteResultOperation getUpdateTransactionCompleteResponse() {
            return updateTransactionCompleteResponse;
        }

        /**
         * Sets the value of the updateTransactionCompleteResponse property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTransactionCompleteResultOperation }
         *     
         */
        public void setUpdateTransactionCompleteResponse(UpdateTransactionCompleteResultOperation value) {
            this.updateTransactionCompleteResponse = value;
        }

    }

}
